"""Add ExpertBlogPosts resource

Revision ID: 1f922b647cb3
Revises: 66c374ede646
Create Date: 2024-05-15 23:57:09.406614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f922b647cb3'
down_revision = '66c374ede646'
branch_labels = None
depends_on = None


def upgrade():
    # Add the expert_id column without a NOT NULL constraint
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_id', sa.Integer(), nullable=True))  # Allow NULL values initially

    # Create the foreign key constraint
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_blogpost_expert', 'expert', ['expert_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogpost_expert', type_='foreignkey')
        batch_op.drop_column('expert_id')

    # ### end Alembic commands ###
