# """Total Likes

# Revision ID: a8041c54361e
# Revises: 1f922b647cb3
# Create Date: 2024-05-16 19:44:37.028494

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = 'a8041c54361e'
# down_revision = '1f922b647cb3'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('blog_post', schema=None) as batch_op:
#         batch_op.alter_column('expert_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)

#     with op.batch_alter_table('like', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
#         batch_op.drop_column('created_at')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('like', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
#         batch_op.drop_column('total')

#     with op.batch_alter_table('blog_post', schema=None) as batch_op:
#         batch_op.alter_column('expert_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)

#     # ### end Alembic commands ###

"""Total Likes

Revision ID: a8041c54361e
Revises: 1f922b647cb3
Create Date: 2024-05-16 19:44:37.028494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8041c54361e'
down_revision = '1f922b647cb3'
branch_labels = None
depends_on = None


def upgrade():
    # Drop the temporary table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_blog_post")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('expert_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('total')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('expert_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
