# """Rename back references for messages_sent and messages_received relationships

# Revision ID: fbbb882c86e9
# Revises: 19642e13136e
# Create Date: 2024-05-24 13:15:17.215526

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = 'fbbb882c86e9'
# down_revision = '19642e13136e'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('_alembic_tmp_message')
#     with op.batch_alter_table('message', schema=None) as batch_op:
#         batch_op.alter_column('content',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Text(),
#                existing_nullable=True)
#         batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('message', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.alter_column('content',
#                existing_type=sa.Text(),
#                type_=sa.VARCHAR(),
#                existing_nullable=True)

#     op.create_table('_alembic_tmp_message',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('content', sa.TEXT(), nullable=True),
#     sa.Column('sender_id', sa.INTEGER(), nullable=False),
#     sa.Column('receiver_id', sa.INTEGER(), nullable=False),
#     sa.Column('created_at', sa.DATETIME(), nullable=True),
#     sa.Column('conversation_id', sa.INTEGER(), nullable=True),
#     sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
#     sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###
"""Rename back references for messages_sent and messages_received relationships

Revision ID: fbbb882c86e9
Revises: 19642e13136e
Create Date: 2022-01-01 00:00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'fbbb882c86e9'
down_revision = '19642e13136e'
branch_labels = None
depends_on = None


def upgrade():
    # Check if _alembic_tmp_message table exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    if not inspector.has_table('_alembic_tmp_message'):
        # Create the table only if it doesn't exist
        op.create_table('_alembic_tmp_message',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('content', sa.Text(), nullable=True),
            sa.Column('sender_id', sa.Integer(), nullable=False),
            sa.Column('receiver_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('conversation_id', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['receiver_id'], ['user.id']),
            sa.ForeignKeyConstraint(['sender_id'], ['user.id'])
        )


def downgrade():
    # Drop the _alembic_tmp_message table
    op.drop_table('_alembic_tmp_message')
